apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-idler-data-longhorn-pvc
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
