apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tak-server-data-longhorn-pvc
  namespace: tak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
