apiVersion: v1
kind: Service
metadata:
  name: tak-server
  namespace: tak
  labels:
    app: tak-server
spec:
  type: ClusterIP
  selector:
    app: tak-server
  ports:
    - name: http-enrollment
      port: 8089
      targetPort: 8089
    - name: https-api
      port: 8443
      targetPort: 8443
    - name: https-alt
      port: 8444
      targetPort: 8444
    - name: https-fed
      port: 8446
      targetPort: 8446
    - name: http-marti
      port: 8080
      targetPort: 8080
