apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vintage-story-longhorn-pvc
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
