apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-data-longhorn-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
