apiVersion: v1
kind: Service
metadata:
  name: vintage-story-2-service
  namespace: gaming
spec:
  type: ClusterIP
  selector:
    app: vintage-story-2
  ports:
    - name: game-tcp
      protocol: TCP
      port: 42421
      targetPort: 42421
    - name: game-udp
      protocol: UDP
      port: 42421
      targetPort: 42421
