apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server-external
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GITHUB_ORG_PLACEHOLDER/homelab-k8s-public.git
    targetRevision: HEAD
    path: charts/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
